name: device_calendar_example
description: Example of use device_calendar package in flutter app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_calendar: ^0.1.2+2

flutter:
  uses-material-design: true
